# This YAML file defines a Kubernetes cluster configuration for use with Kind (Kubernetes IN Docker).
# The 'kind' field specifies the type of resource being defined, which in this case is a 'Cluster'.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-controller=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 6969
    hostPort: 6969
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  extraMounts:
  - hostPath: /opt/kind/data
    containerPath: /opt/kind/data
- role: worker
  extraMounts:
  - hostPath: /opt/kind/data
    containerPath: /opt/kind/data
- role: worker
  extraMounts:
  - hostPath: /opt/kind/data
    containerPath: /opt/kind/data
