apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: koyun
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: koyun
spec:
  dnsNames:
  - "*.tls-nodes.koyun.svc.cluster.local"
  secretName: rabbitmq-cert-secret
  duration: "73560h"
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
