apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    app: rabbitmq
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
  storageClassName: koyun-rabbitmq-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /koyun/data/rabbitmq
