apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: koyun-postgres-hostpath
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /koyun/data/postgresql
