apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: koyun
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: a295dW4=
  POSTGRES_USER: a295dW4=
  POSTGRES_PASSWORD: S295dW5Vc2VyXzIwMjAh
